---
title: "Assignment1"
author: "crator-creator/20162306임유석"
date: '2021 3 22 '
output: html_document
---

<br/>

### Metro Dataset (2019/11)

<br/>

#### 1. 숭실대입구역의 11월1일의 시간대별 승차 및 하차 인원 수를 하나의 그래프로 시각화해보자

<br/>


```{r message=FALSE}
# 사용할 패키지 추가
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggthemes)
library(ggmap)
```

```{r graph1}
#파일 읽기
Metro = read.csv("metro.csv")
#숭실대역, 날짜로 인덱싱
Metro_ssu = subset(Metro, Metro$"역명" == "숭실대입구(살피재)" & Metro$날짜=="2019-11-01")
#시간을 한 칼럼으로 만들기, 시간, 승차, 하차 시간이 들어있는 데이터프레임 만들기
Metro_ssu_up = t(Metro_ssu[-1:-5][1,])
Metro_ssu_down = t(Metro_ssu[-1:-5][2,])
d3 = data.frame(Metro_ssu_up, Metro_ssu_down)
up = as.numeric(d3[['X473']][-1])
down = as.numeric(d3[['X474']][-1])
time = c('04-05','05-06','06-07','07-08','08-09','09-10','10-11','11-12','12-13','13-14','14-15','15-16','16-17','17-18','18-19','19-20','20-21','21-22','22-23','23-24','00-01','01-02','02-03','03-04')
Metro_ssu_upDown= data.frame(time,up,down)
Metro_ssu_upDown
#그래프 출력
ggplot(Metro_ssu_upDown, aes(x=time, group=1)) + geom_line(aes(y=up, color="con")) + geom_line(aes(y=down,color="cur")) + labs(title='11/1시간대별 승차 및 하차 인원 수', x="시간",y="인원 수", color="승/하차 인원")  +scale_color_manual(breaks=c("con", "cur"),labels=c("승차", "하차"), values=c("red", "black")) + theme(axis.text.x = element_text(angle=50, hjust=1))
```
<br/>

#### 2. 숭실대입구역의 11월4일부터 11월10일까지 일주일간 각 요일별 시간대별 승차인원과 하차인원의 분포를 각각 히트맵으로 시각화해보자

<br/>


```{r graph2}
#4일부터 10일까지 승하차 인원
Metro_ssu = subset(Metro, Metro$"역명" == "숭실대입구(살피재)")[7:20,]
#필요없는 칼럼 제거
Metro_ssu = Metro_ssu[c(-1,-3,-4,-5)]
#요일별 승차 인원 수
up_day=Metro_ssu[-c(2,4,6,8,10,12,14),]
#요일,시간,횟수 데이터 프레임 생성(승차)
day=c()
time=c()
freq=c()
for(i in 0:3){
	timex = c(i,i,i,i,i,i,i)
	time=c(time,timex)
	x=c("mon","tue","wed","thur","fri","sat","sun")
	day = c(day, x)
	freq_a = t(up_day[-2])[i+22,]
	freq=c(freq, freq_a)
}
for ( i in 2:21){
	timex = c(i+2,i+2,i+2,i+2,i+2,i+2,i+2)
	time = c(time, timex)
	x=c("mon","tue","wed","thur","fri","sat","sun")
	day = c(day, x)
	freq_a = t(up_day[-2])[i,]
	freq=c(freq, freq_a)
}
freq = as.numeric(freq)
day = factor(day)
result = data.frame(day,time,freq)
result
#승차 그래프 시각화
ggplot(result, aes(x=time, y=day, fill=freq))+ geom_tile()+theme_minimal()+labs(title= "요일,시간별 지하철 승차 인원", subtitle="ssu_11/4~11/10", x="시각",y="요일")

#요일별 하차 인원 수
down_day=Metro_ssu[-c(1,3,5,7,9,11,13),]
#요일,시간,횟수 데이터 프레임 생성(하차)
day_d=c()
time_d=c()
freq_d=c()
for(i in 0:3){
	timex = c(i,i,i,i,i,i,i)
	time_d=c(time_d,timex)
	x=c("mon","tue","wed","thur","fri","sat","sun")
	day_d = c(day_d, x)
	freq_b = t(down_day[-2])[i+22,]
	freq_d=c(freq_d, freq_b)
}
for ( i in 2:21){
	timex = c(i+2,i+2,i+2,i+2,i+2,i+2,i+2)
	time_d = c(time_d, timex)
	x=c("mon","tue","wed","thur","fri","sat","sun")
	day_d = c(day_d, x)
	freq_b = t(down_day[-2])[i,]
	freq_d=c(freq_d, freq_b)
}
freq_d = as.numeric(freq_d)
day_d = factor(day_d)
result_d = data.frame(day_d,time_d,freq_d)
result_d
ggplot(result_d, aes(x=time_d, y=day_d, fill=freq_d))+ geom_tile()+theme_minimal()+labs(title= "요일,시간별 지하철 하차 인원", subtitle="ssu_11/4~11/10", x="시각",y="요일")


```

<br/>

#### 3. 7호선의 모든 역 중에서 유동인구(월간 승하차 전체인원)가 가장 많은 20개 역에 대한 유동인구 수를 그래프로 시각화해보자

<br/>
```{r graph3}
#시간별로 있는 유동인구를 날짜별로 통합하기
x=as.matrix(Metro[7:30])
sum=apply(x,1,sum)
Metro_re=Metro[-7:-30]
Metro_re$sum = sum
#7호선 데이터 식별 및 역별 월간 승하차 인원 데이터프레임
Metro_re = Metro_re[(Metro_re$호선 == "7호선"),]
Metro_re = Metro_re[-1:-4][-2]
#역명이 같은 데이터 합하기
Metro_month=aggregate(Metro_re$sum, by=list(Metro_re$역명),sum)
#내림차순 정렬
Metro_DESC=Metro_month[order(Metro_month$x, decreasing=TRUE),]
#상위20개역 자르기
Metro_twenty=Metro_DESC[1:20,]
#그래프 시각화
ggplot(Metro_twenty, aes(x=reorder(Group.1,x), y=x))+geom_bar(stat="identity") + theme(axis.text.x = element_text(angle=60, hjust=1))+labs(title="7호선 상위20개역 유동인구", x="7호선역", y="유동인구수")
```

<br/>

#### 4. 7호선 모든 역에 대한 유동인구 분포를 지도 위에 시각화해보자.

<br/>

```{r graph4}
#위도경도 파일 읽기
LatLons = read.csv("metro_coord.csv")
#불필요한 칼럼 제거
LatLons=LatLons[-1:-2][-2]
#유동인구 정보 결합
LatLons$freq = Metro_month$x
#stamenmap이 소수2째자리까지 인식.
LatLons$lat = round(LatLons$lat,2)
LatLons$lon = round(LatLons$lon,2)
LatLons$freq = as.integer(LatLons$freq)
LatLons
#서울 좌표 가져오기
bbox_seoul <- c(left = 126.826128, bottom = 37.458073, 
 right = 127.194848, top = 37.696073)
#맵 정보 가져오기
seoul <- get_stamenmap(bbox = bbox_seoul, zoom = 10, maptype = "toner")
#시각화
ggmap(seoul,base_layer =ggplot(data = LatLons,aes(x=lon, y = lat, alpha=freq))) + geom_tile(fill='blue',na.rm=TRUE)+theme_void() + labs(title="7호선역 유동인구 분포", subtitle="11월")

```
